language: cpp

compiler:
  - gcc

before_install:
  - sudo apt update && sudo apt install -y gcc cmake lcov ggcov build-essential libboost-all-dev git-core

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - make cpp-computing-fundamentals cpp-computing-fundamentals-coverage
  - mv coverage/ ../docs
