language: cpp
dist: bionic

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install gcc-7.4.0 -y
  - pip install --user cpp-coveralls
  - sudo apt install -y cmake lcov ggcov build-essential libboost-all-dev git-core doxygen

script:
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make cpp-computing-fundamentals cpp-computing-fundamentals-coverage

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"

addons:
  apt:
    update: true