language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls
  - sudo apt install -y gcc cmake lcov ggcov build-essential libboost-all-dev git-core doxygen

script:
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make cpp-computing-fundamentals cpp-computing-fundamentals-coverage

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"

addons:
  apt:
    update: true